=== Filip-Rusiecki/XMLGen/project_lib/contacts.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="allcontacts" type="allcontactsType"/>
    <xs:complexType name="contactType">
        <xs:sequence>
            <xs:element type="xs:string" name="firstname"/>
            <xs:element type="xs:string" name="lastname"/>
            <xs:element type="xs:string" name="email"/>
            <xs:element type="xs:string" name="country"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="id" use="required"/>
    </xs:complexType>
    <xs:complexType name="allcontactsType">
        <xs:sequence>
            <xs:element type="contactType" name="contact" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Filip-Rusiecki/XMLGen/contacts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<allcontacts xmlns:xsi="http:www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation ="contacts.xsd">
<contact id="453">
<firstname>Jami</firstname>
<lastname>Wynes</lastname>
<email>jwynesck@people.com.cn</email>
<country>Finland
</country>
</contact>
<contact id="454">
<firstname>Sela</firstname>
<lastname>McCarty</lastname>
<email>smccartycl@prnewswire.com</email>
<country>China
</country>
</contact>
<contact id="455">
<firstname>Krystalle</firstname>
<lastname>Gleader</lastname>
<email>kgleadercm@dedecms.com</email>
<country>Ukraine
</country>
</contact>
<contact id="456">
<firstname>Corrie</firstname>
<lastname>Shenfisch</lastname>
<email>cshenfischcn@nature.com</email>
<country>China
</country>
</contact>
<contact id="457">
<firstname>Gavin</firstname>
<lastname>Alder</lastname>
<email>galderco@yolasite.com</email>
<country>Chile
</country>
</contact>
<contact id="458">
<firstname>Fern</firstname>
<lastname>Kegan</lastname>
<email>fkegancp@addthis.com</email>
<country>China
</country>
</contact>
<contact id="459">
<firstname>Phillipe</firstname>
<lastname>Schwandermann</lastname>
<email>pschwandermanncq@posterous.com</email>
<country>Japan
</country>
</contact>
<contact id="460">
<firstname>Brooke</firstname>
<lastname>Molineux</lastname>
<email>bmolineuxcr@cnbc.com</email>
<country>Malaysia
</country>
</contact>
<contact id="461">
<firstname>Rosalynd</firstname>
<lastname>Denne</lastname>
<email>rdennecs@intel.com</email>
<country>Czech Republic
</country>
</contact>
<contact id="462">
<firstname>Almira</firstname>
<lastname>Kitchingman</lastname>
<email>akitchingmanct@boston.com</email>
<country>Morocco
</country>
</contact>
<contact id="463">
<firstname>Danica</firstname>
<lastname>Nice</lastname>
<email>dnicecu@ocn.ne.jp</email>
<country>Netherlands
</country>
</contact>
<contact id="464">
<firstname>Rutger</firstname>
<lastname>Paddick</lastname>
<email>rpaddickcv@slate.com</email>
<country>France
</country>
</contact>
<contact id="465">
<firstname>Dotty</firstname>
<lastname>Harnott</lastname>
<email>dharnottcw@weibo.com</email>
<country>Tanzania
</country>
</contact>
<contact id="466">
<firstname>Fiann</firstname>
<lastname>Kingescot</lastname>
<email>fkingescotcx@tripadvisor.com</email>
<country>Brazil
</country>
</contact>
<contact id="467">
<firstname>Phoebe</firstname>
<lastname>Yantsev</lastname>
<email>pyantsevcy@creativecommons.org</email>
<country>China
</country>
</contact>
<contact id="468">
<firstname>Angelia</firstname>
<lastname>Whales</lastname>
<email>awhalescz@yahoo.co.jp</email>
<country>Indonesia
</country>
</contact>
<contact id="469">
<firstname>Worthy</firstname>
<lastname>Smalls</lastname>
<email>wsmallsd0@seattletimes.com</email>
<country>Sweden
</country>
</contact>
<contact id="470">
<firstname>Ealasaid</firstname>
<lastname>Rikkard</lastname>
<email>erikkardd1@telegraph.co.uk</email>
<country>Republic of the Congo
</country>
</contact>
<contact id="471">
<firstname>Sally</firstname>
<lastname>Downs</lastname>
<email>sdownsd2@yellowbook.com</email>
<country>Russia
</country>
</contact>
<contact id="472">
<firstname>Gill</firstname>
<lastname>Yvens</lastname>
<email>gyvensd3@networkadvertising.org</email>
<country>Brazil
</country>
</contact>
<contact id="473">
<firstname>Kary</firstname>
<lastname>Concannon</lastname>
<email>kconcannond4@addtoany.com</email>
<country>Venezuela
</country>
</contact>
<contact id="474">
<firstname>Dyanne</firstname>
<lastname>Keysall</lastname>
<email>dkeysalld5@cpanel.net</email>
<country>Russia
</country>
</contact>
<contact id="475">
<firstname>Abbie</firstname>
<lastname>Radbourn</lastname>
<email>aradbournd6@marriott.com</email>
<country>Peru
</country>
</contact>
<contact id="476">
<firstname>Clerissa</firstname>
<lastname>Keoghane</lastname>
<email>ckeoghaned7@1688.com</email>
<country>Indonesia
</country>
</contact>
<contact id="477">
<firstname>Lynn</firstname>
<lastname>Card</lastname>
<email>lcardd8@usda.gov</email>
<country>Guatemala
</country>
</contact>
<contact id="478">
<firstname>Haze</firstname>
<lastname>Muscott</lastname>
<email>hmuscottd9@biblegateway.com</email>
<country>Serbia
</country>
</contact>
<contact id="479">
<firstname>Frasco</firstname>
<lastname>Syplus</lastname>
<email>fsyplusda@cisco.com</email>
<country>France
</country>
</contact>
<contact id="480">
<firstname>Dniren</firstname>
<lastname>Toplis</lastname>
<email>dtoplisdb@homestead.com</email>
<country>Indonesia
</country>
</contact>
<contact id="481">
<firstname>Andrea</firstname>
<lastname>Gummory</lastname>
<email>agummorydc@unblog.fr</email>
<country>Gambia
</country>
</contact>
<contact id="482">
<firstname>Julio</firstname>
<lastname>Brewster</lastname>
<email>jbrewsterdd@archive.org</email>
<country>China
</country>
</contact>
<contact id="483">
<firstname>Demott</firstname>
<lastname>Allgood</lastname>
<email>dallgoodde@apple.com</email>
<country>China
</country>
</contact>
<contact id="484">
<firstname>Sherry</firstname>
<lastname>Pitkeathly</lastname>
<email>spitkeathlydf@wikispaces.com</email>
<country>Sweden
</country>
</contact>
<contact id="485">
<firstname>Marchelle</firstname>
<lastname>Cattach</lastname>
<email>mcattachdg@craigslist.org</email>
<country>Kazakhstan
</country>
</contact>
<contact id="486">
<firstname>Albina</firstname>
<lastname>Koeppke</lastname>
<email>akoeppkedh@engadget.com</email>
<country>China
</country>
</contact>
<contact id="487">
<firstname>Karlotte</firstname>
<lastname>Creser</lastname>
<email>kcreserdi@whitehouse.gov</email>
<country>Mexico
</country>
</contact>
<contact id="488">
<firstname>Kristofor</firstname>
<lastname>Crepel</lastname>
<email>kcrepeldj@va.gov</email>
<country>Colombia
</country>
</contact>
<contact id="489">
<firstname>Myrta</firstname>
<lastname>O'Murtagh</lastname>
<email>momurtaghdk@xrea.com</email>
<country>Greece
</country>
</contact>
<contact id="490">
<firstname>Jeremias</firstname>
<lastname>Blabber</lastname>
<email>jblabberdl@miitbeian.gov.cn</email>
<country>China
</country>
</contact>
<contact id="491">
<firstname>Brockie</firstname>
<lastname>Vertigan</lastname>
<email>bvertigandm@deviantart.com</email>
<country>China
</country>
</contact>
<contact id="492">
<firstname>Fae</firstname>
<lastname>Rodenborch</lastname>
<email>frodenborchdn@scribd.com</email>
<country>China
</country>
</contact>
<contact id="493">
<firstname>Sam</firstname>
<lastname>Toyne</lastname>
<email>stoynedo@marriott.com</email>
<country>Russia
</country>
</contact>
<contact id="494">
<firstname>Rycca</firstname>
<lastname>Kingswood</lastname>
<email>rkingswooddp@scribd.com</email>
<country>China
</country>
</contact>
<contact id="495">
<firstname>Conny</firstname>
<lastname>Norrey</lastname>
<email>cnorreydq@harvard.edu</email>
<country>Russia
</country>
</contact>
<contact id="496">
<firstname>Berrie</firstname>
<lastname>Demelt</lastname>
<email>bdemeltdr@meetup.com</email>
<country>Philippines
</country>
</contact>
<contact id="497">
<firstname>Beatriz</firstname>
<lastname>Spackman</lastname>
<email>bspackmands@123-reg.co.uk</email>
<country>China
</country>
</contact>
<contact id="498">
<firstname>Daryn</firstname>
<lastname>Greenman</lastname>
<email>dgreenmandt@i2i.jp</email>
<country>China
</country>
</contact>
<contact id="499">
<firstname>Agnola</firstname>
<lastname>Callister</lastname>
<email>acallisterdu@ezinearticles.com</email>
<country>Indonesia
</country>
</contact>
<contact id="500">
<firstname>Harriot</firstname>
<lastname>Chippindall</lastname>
<email>hchippindalldv@nbcnews.com</email>
<country>Brazil
</country>
</contact>
<contact id="501">
<firstname>Emelita</firstname>
<lastname>Moxley</lastname>
<email>emoxleydw@networkadvertising.org</email>
<country>Montenegro
</country>
</contact>
<contact id="502">
<firstname>Maddy</firstname>
<lastname>Accombe</lastname>
<email>maccombedx@wordpress.com</email>
<country>Portugal
</country>
</contact>
<contact id="503">
<firstname>Ethe</firstname>
<lastname>Punch</lastname>
<email>epunchdy@goodreads.com</email>
<country>Brazil
</country>
</contact>
<contact id="504">
<firstname>Briggs</firstname>
<lastname>Gatherer</lastname>
<email>bgathererdz@mayoclinic.com</email>
<country>Russia
</country>
</contact>
<contact id="505">
<firstname>Nanni</firstname>
<lastname>Renehan</lastname>
<email>nrenehane0@taobao.com</email>
<country>China
</country>
</contact>
<contact id="506">
<firstname>Camel</firstname>
<lastname>Gilfether</lastname>
<email>cgilfethere1@oracle.com</email>
<country>Poland
</country>
</contact>
<contact id="507">
<firstname>Mariana</firstname>
<lastname>Bergin</lastname>
<email>mbergine2@ihg.com</email>
<country>Russia
</country>
</contact>
<contact id="508">
<firstname>Shaw</firstname>
<lastname>Eadie</lastname>
<email>seadiee3@forbes.com</email>
<country>Sudan
</country>
</contact>
<contact id="509">
<firstname>Lyman</firstname>
<lastname>Meins</lastname>
<email>lmeinse4@rakuten.co.jp</email>
<country>South Korea
</country>
</contact>
<contact id="510">
<firstname>Tobey</firstname>
<lastname>Panner</lastname>
<email>tpannere5@nih.gov</email>
<country>China
</country>
</contact>
<contact id="511">
<firstname>Thalia</firstname>
<lastname>Patton</lastname>
<email>tpattone6@odnoklassniki.ru</email>
<country>Russia
</country>
</contact>
<contact id="512">
<firstname>Dorise</firstname>
<lastname>O'Gormally</lastname>
<email>dogormallye7@walmart.com</email>
<country>China
</country>
</contact>
<contact id="513">
<firstname>Joellyn</firstname>
<lastname>Coche</lastname>
<email>jcochee8@ovh.net</email>
<country>Sweden
</country>
</contact>
<contact id="514">
<firstname>Row</firstname>
<lastname>Treble</lastname>
<email>rtreblee9@engadget.com</email>
<country>Tanzania
</country>
</contact>
<contact id="515">
<firstname>Augy</firstname>
<lastname>Ferronet</lastname>
<email>aferronetea@nydailynews.com</email>
<country>Russia
</country>
</contact>
<contact id="516">
